"""Export the Blender-modelled flower heads to the game: src/sim/orchid-heads.js (generated; do not edit by hand).
   blender -b --factory-startup -P art-src/orchids/export_heads.py -- <out.js> [species ...]
Each species module (art-src/orchids/<species>.py) defines build(form) -> [Part]; form 0 is the geometry (forms differ only by palette)."""
import sys, os, json, importlib.util
HERE = os.path.dirname(os.path.abspath(__file__)); sys.path.insert(0, HERE)
import orchidlib as ol

def load(sp):
    spec = importlib.util.spec_from_file_location(sp, os.path.join(HERE, sp + ".py")); m = importlib.util.module_from_spec(spec); spec.loader.exec_module(m); return m

def compact(d):
    n = len(d["pos"]) // 3
    msk = []
    for k in range(n):
        r, g = round(d["msk"][3 * k], 3), round(d["msk"][3 * k + 1], 3)
        if r + g > 1: g = round(1 - r, 3)
        msk += [r, g]
    return dict(pos=d["pos"], nor=d["nor"], uv=d["uv"], msk=msk, at=d["at"], idx=d["idx"])

if __name__ == "__main__":
    a = sys.argv[sys.argv.index("--") + 1:]
    out, species = a[0], a[1:]
    heads = {}
    for sp in species:
        parts = load(sp).build(0)
        heads[sp] = compact(ol.export_all(parts))
        print("HEAD", sp, "tris", ol.tri_count(parts), "verts", len(heads[sp]["pos"]) // 3)
    body = ",\n".join("  %s: %s" % (sp, json.dumps(h, separators=(",", ":"))) for sp, h in heads.items())
    open(out, "w").write(
        "// GENERATED by art-src/orchids/export_heads.py from the Blender flower models (art-src/orchids/<species>.py): do not edit by hand.\n"
        "// One flower head per species in head space (+Y the facing, +Z the top; 1 unit = 1 cm): pos and nor (xyz), uv (leaf u, v; v -1 = a solid part),\n"
        "// msk (palette mask main, accent per vertex; centre = 1 - main - accent), at (atlas x, y per vertex in the petal atlas, -1 = none: the old arithmetic patterns), idx (triangles). sim/flowering.js bakedHead() replays it.\n"
        "export const HEADS = {\n" + body + ",\n};\n")
    print("WROTE", out, os.path.getsize(out), "bytes")
