// Real habitats to copy. Each says what the place is like (temperature and
// humidity targets from field data), who lives there (animals and plants the
// game has), and which features make it recognisable. The Curator scores a
// tank against its chosen biotope; commissions ask for them by name.

import { SHOWCASE_BIOTOPES } from './presets-showcase.js';

export const BIOTOPES = {
  newguinea: {
    id: 'newguinea', name: 'New Guinea stream bank', country: 'Papua New Guinea', level: 7,
    animals: ['skink', 'purpleiso', 'isopod', 'springtail'], plants: ['fern', 'cattail', 'grass', 'pothos', 'nidus', 'sago', 'pandanus'],
    climate: { temp: [23, 28], humidity: [80, 98] },
    features: ['leaflitter', 'shallowpool', 'basking', 'uvb'],
    blurb: 'Humid lowland forest floor beside a creek: deep leaf litter, rotting logs and the roots of sago palms. The red-eyed crocodile skink lives here, hidden by day and out at dusk to hunt insects and worms along the water.',
    facts: ['The skink lays a single egg at a time, often in a damp burrow under a log.', 'Crocodile skinks can squeak: one of the few lizards that make a sound when handled.'],
    hint: '80% land with deep litter, cork and wood to hide under, a shallow pool, a mild warm spot and low UVB, 80% humidity or more.',
  },
  madagascar: {
    id: 'madagascar', name: 'Madagascar reed marsh', country: 'Madagascar', level: 6,
    animals: ['reedfrog', 'springtail', 'fly', 'bedotia'], plants: ['cattail', 'bamboo', 'grass', 'lily', 'fern', 'vallisneria', 'aponogeton', 'pandanus'],
    climate: { temp: [24, 29], humidity: [70, 90] },
    features: ['deep', 'tall4'],
    blurb: 'Reeds and shrubs around marshes and paddies in southern and eastern Madagascar. Starry night reed frogs sit high on stems and leaves above the water by day and call in chorus from them in the rainy season.',
    facts: ['Reed frogs sit flat on a leaf with their legs tucked in to save water in the heat of the day.', 'Their eggs are laid in the water below, so the tadpoles drop straight into a pond.'],
    hint: 'A tall tank, mostly water, with sedges, reeds and stems above it to perch on.',
  },
  matano: {
    id: 'matano', name: 'Lake Matano shore', country: 'Indonesia', level: 7,
    animals: ['panther', 'snail', 'matanoshrimp', 'tylomelania'], plants: ['vallisneria', 'grass', 'javafern', 'pothos'],
    climate: { temp: [24, 28], humidity: [70, 100] },
    features: ['deep', 'hardwater', 'stones', 'wood'],
    blurb: 'An ancient, very deep lake in the mountains of Sulawesi with clear, warm, alkaline water. Panther crabs live among the rocks and sunken wood of its shore, beside snails and shrimp found nowhere else.',
    facts: ['Lake Matano is more than a million years old and 590 m deep, one of the oldest lakes on Earth.', 'Its water is low in nutrients and rich in minerals, so it is extremely clear.'],
    hint: 'Deep, hard water (GH 10 or more), stones and wood that reach out of it, strong filtration.',
  },
  everglades: {
    id: 'everglades', name: 'Everglades swamp margin', country: 'United States', level: 5,
    animals: ['pygmy', 'springtail', 'isopod'], plants: ['cattail', 'grass', 'fern', 'lily', 'fissidens', 'limnobium'],
    climate: { temp: [18, 26], humidity: [65, 95] },
    features: ['stillwater', 'shallowpool', 'moss15'],
    blurb: 'Weedy, still margins of the Florida swamps, thick with stems, floating plants and mats of vegetation. The Everglades pygmy sunfish hangs among the stems waiting for tiny crustaceans to drift by.',
    facts: ['The swamp cools in winter: these fish need a cooler spell to breed well.', 'A displaying male turns velvet black with blue spangles.'],
    hint: 'Still water, thick with stems and floating plants; no strong filter.',
  },
  suriname: {
    id: 'suriname', name: 'Suriname forest island', country: 'Suriname', level: 4,
    animals: ['dartfrog', 'springtail', 'isopod', 'fly'], plants: ['bromeliad', 'guzmania', 'fern', 'grass', 'monstera', 'tillandsia'],
    climate: { temp: [23, 28], humidity: [80, 97] },
    features: ['bromeliad2', 'leaflitter', 'shallowpool'],
    blurb: 'Islands of forest in open savanna. Days are warm and humid, nights cooler, and there is a clear wet and dry season. The blue poison frog lives among the roots and leaf litter of these islands and its tadpoles grow in bromeliad cups.',
    facts: ['The savanna between the forest islands is dry and bright, so each island is a pocket of moisture the frogs cannot leave.', 'Each island holds its own small frog population, which is why so many local colour forms exist.'],
    hint: 'Dense plants and moss on the ground, bromeliads above the waterline, a shallow pool, 80%+ humidity.',
  },
  bocas: {
    id: 'bocas', name: 'Bocas del Toro lowland forest', country: 'Panama', level: 5,
    animals: ['strawberry', 'springtail', 'isopod', 'fly'], plants: ['guzmania', 'bromeliad', 'columnea', 'pleurothallis', 'lepanthes', 'fern', 'grass', 'monstera', 'tillandsia'],
    climate: { temp: [24, 29], humidity: [85, 100] },
    features: ['bromeliad3', 'moss15', 'stream'],
    blurb: 'Rain falls on more than 200 days a year on the Caribbean coast of Panama. Strawberry poison frogs live in leaf litter and low bromeliads. Each island has its own colour, from red with blue legs to green, orange and white.',
    facts: ['Females feed their tadpoles unfertilised eggs, one tadpole per bromeliad.', 'The frogs are tiny: an adult is under 2.5 cm long.'],
    hint: 'Constant humidity, lots of moss and litter, three or more bromeliads, and a small stream.',
  },
  blackwater: {
    id: 'blackwater', name: 'Rio Negro blackwater', country: 'Brazil', level: 4,
    animals: ['cardinal', 'cory'], plants: ['sword', 'frogbit', 'fern', 'grass', 'monstera', 'bromeliad'],
    climate: { temp: [24, 29], humidity: [70, 100] },
    features: ['wood', 'deep', 'cycled'],
    blurb: 'The Rio Negro is stained the colour of tea by tannins from the forest. The water is acidic and nearly sterile. Fish here live among fallen wood, leaf litter and the trunks of trees that flood every year.',
    facts: ['Blackwater has almost no nutrients, so few aquatic plants can grow in it. Most of the food comes from the forest.', 'The tannins stain light, so the river looks black from above.'],
    hint: 'A deep lagoon, driftwood, a school of small tetras, and clean cycled water.',
  },
  korea: {
    id: 'korea', name: 'Korean mountain stream', country: 'South Korea', level: 6,
    animals: ['toad', 'shrimp', 'springtail', 'isopod', 'fly', 'zacco'], plants: ['fernph', 'grass', 'vallisneria', 'cattail', 'javamoss', 'miscanthus'],
    climate: { temp: [16, 24], humidity: [60, 90] },
    features: ['stream', 'shallowpool', 'moss15'],
    blurb: 'Cool hills with slow streams and rice paddies. The fire-bellied toad lives in ponds and stream margins where the water is shallow and the temperature rarely rises above the low twenties.',
    facts: ['It hibernates in winter, and the cold snap helps trigger breeding in spring.', 'It is common enough to be found in paddies.'],
    hint: 'Cool: keep it under 24 °C with a fan or a cooling unit; ferns and grass, a slow stream, a shallow pool.',
  },
  china: {
    id: 'china', name: 'Chinese mountain torrent', country: 'China', level: 7,
    animals: ['newt', 'shrimp', 'springtail', 'isopod', 'tanichthys', 'hillloach'], plants: ['javafern', 'fernph', 'fern', 'grass', 'vallisneria', 'pothos', 'javamoss', 'cattail', 'bamboo', 'crypt', 'nidus', 'miscanthus'],
    climate: { temp: [14, 23], humidity: [70, 95] },
    features: ['falls', 'oxygen', 'stones'],
    blurb: 'Cool, shaded, fast streams under mixed forest. The paddle-tailed newt clings to the bottom under stones in fast, well-oxygenated water.',
    facts: ['Oxygen dissolves better in cold, turbulent water.', 'Many of these streams are shrinking as forests are cleared.'],
    hint: 'A waterfall for oxygen, cool water (under 23 °C), lots of stones.',
  },
  java: {
    id: 'java', name: 'Javan stream bank', country: 'Indonesia', level: 5,
    animals: ['crab', 'isopod', 'springtail'], plants: ['fern', 'cattail', 'grass', 'javamoss', 'pothos', 'javafern', 'vallisneria', 'bamboo', 'nidus'],
    climate: { temp: [24, 29], humidity: [80, 98] },
    features: ['shallowpool', 'moss15', 'stones'],
    blurb: 'On the forest floor of Java, small streams run over volcanic rock. Vampire crabs live on the banks: half on land, half in water, and breed on land.',
    facts: ['They dig burrows in the wet soil beside streams.', 'The young are miniature crabs that skip the swimming larval stage.'],
    hint: 'Damp soil, stones, shallow water and land beside it; a lid.',
  },
  xochimilco: {
    id: 'xochimilco', name: 'Xochimilco canals', country: 'Mexico', level: 8,
    animals: ['axolotl', 'cambarellus'], plants: ['vallisneria', 'frogbit', 'lily', 'grass', 'cattail'],
    climate: { temp: [14, 20], humidity: [50, 95] },
    features: ['deep', 'cycled', 'cool'],
    blurb: 'A network of canals in the south of Mexico City: the last home of the axolotl. Cool, shallow water beside floating gardens, at 2,200 metres above sea level.',
    facts: ['Introduced carp and tilapia eat axolotls and their eggs, and pollution threatens the water.', 'Local farmers build reed-fenced refuges to protect the animals.'],
    hint: 'Cold water (under 20 °C): needs a cooling unit. Clean, planted and cool.',
  },
  pacific: {
    id: 'pacific', name: 'Pacific palm grove', country: 'Fiji', level: 5,
    animals: ['gecko', 'fly', 'springtail', 'isopod'], plants: ['cattail', 'grass', 'fern', 'pothos', 'nidus'],
    climate: { temp: [23, 30], humidity: [55, 85] },
    features: ['tall4', 'basking'],
    blurb: 'On Pacific islands mourning geckos live in palms, on walls and roofs, and hunt around lamps at night. They favour warm, humid but airy places, with plenty to climb.',
    facts: ['They colonised islands across the Pacific by rafting on floating debris.', 'They call with a soft chirp.'],
    hint: 'Vertical plants and a basking spot; less soggy than a frog tank.',
  },
  // N15 batch 2: places of the new premade sets (not in BIOTOPE_ORDER, so commissions are unchanged).
  costarica: {
    id: 'costarica', name: 'Tortuguero lowland rainforest', country: 'Costa Rica', level: 5,
    animals: ['redeye', 'springtail', 'isopod', 'fly'], plants: ['monstera', 'columnea', 'guzmania', 'tillandsia', 'bromeliad', 'fern', 'grass', 'frogbit', 'sword', 'heliconia'],
    climate: { temp: [24, 28], humidity: [80, 90] },
    features: ['deep', 'tall4', 'bromeliad2'],
    blurb: 'Wet lowland forest on the Caribbean coast of Costa Rica, cut by canals and pools. Red-eyed tree frogs sleep by day on the underside of leaves and lay their eggs on leaves over the water.',
    facts: ['The eggs hatch early if a snake attacks the clutch: the embryos feel the vibration.', 'Tortuguero gets several metres of rain a year.'],
    hint: 'A tall tank, much of it water, with broad leaves and stems over the pool.',
  },
  cacao: {
    id: 'cacao', name: 'Panama cacao grove', country: 'Panama', level: 5,
    animals: ['auratus', 'springtail', 'isopod', 'fly'], plants: ['monstera', 'columnea', 'guzmania', 'bromeliad', 'fern', 'grass'],
    climate: { temp: [22, 28], humidity: [80, 100] },
    features: ['leaflitter', 'shallowpool'],
    blurb: 'Cacao is grown under the shade of forest trees in western Panama. The leaf litter of these groves stays moist and full of small insects, and green and black poison frogs live in it.',
    facts: ['Shade-grown cacao keeps much of the forest\'s wildlife, unlike open plantations.', 'Green and black poison frogs were introduced to Hawaii in 1932.'],
    hint: 'Deep litter, roots and low plants, high humidity, a small pool.',
  },
  bolivar: {
    id: 'bolivar', name: 'Guiana Shield boulder forest', country: 'Venezuela', level: 5,
    animals: ['leucomelas', 'springtail', 'isopod', 'fly'], plants: ['bromeliad', 'guzmania', 'fern', 'grass', 'tillandsia'],
    climate: { temp: [22, 27], humidity: [70, 95] },
    features: ['leaflitter', 'stones'],
    blurb: 'Forest among granite boulders on the Guiana Shield of southern Venezuela, with a wet and a dry season. The yellow-banded poison frog is active in the open and rests in moist crevices in the dry months.',
    facts: ['The granite of the Guiana Shield is among the oldest rock on Earth.', 'This frog copes with a dry spell better than most poison frogs.'],
    hint: 'Boulders, litter and bromeliads; a drier spell between rains.',
  },
  cordoba: {
    id: 'cordoba', name: 'Sierras de Córdoba grassland', country: 'Argentina', level: 5,
    animals: ['bumblebee', 'springtail', 'isopod'], plants: ['grass', 'bromeliad', 'tillandsia', 'fern', 'tussock'],
    climate: { temp: [20, 24], humidity: [60, 85] },
    features: ['shallowpool', 'stones'],
    blurb: 'Rocky grassland in the hills of central Argentina, with warm rainy summers and cool dry winters. The bumblebee toad walks rather than hops among the tussocks and breeds in rain pools.',
    facts: ['When threatened it shows the bright red underside of its feet.', 'It is active by day, unusual for a toad.'],
    hint: 'Grass, flat stones and very shallow pools; a drier, cooler spell.',
  },
  teutoburg: {
    id: 'teutoburg', name: 'Central European beech wood', country: 'Germany', level: 5,
    animals: ['firesal', 'springtail', 'isopod'], plants: ['fernph', 'weed', 'bilberry', 'grass', 'hartstongue'],
    climate: { temp: [12, 18], humidity: [75, 95] },
    features: ['leaflitter', 'cool', 'stream'],
    blurb: 'Old beech woods with springs and small streams, cool and damp all year. The fire salamander hides under logs and leaves by day and comes out on rainy nights; females put their larvae into clear springs.',
    facts: ['Fire salamanders can live for more than 20 years.', 'A fungus spread by the pet trade, Bsal, is killing fire salamanders in parts of Europe.'],
    hint: 'Cool (under 20 °C), deep litter and logs, a seep of shallow water.',
  },
  galicia: {
    id: 'galicia', name: 'Galician oak-wood pond', country: 'Spain', level: 5,
    animals: ['marbled', 'springtail', 'isopod'], plants: ['cattail', 'lily', 'weed', 'fernph', 'grass', 'vallisneria'],
    climate: { temp: [14, 21], humidity: [70, 95] },
    features: ['deep', 'cool'],
    blurb: 'Ponds in the oak woods of north-west Spain. Marbled newts live on land for most of the year and return to the water in spring, when the males grow a high crest.',
    facts: ['Females wrap each egg in a folded water-plant leaf.', 'Its green marbling camouflages it in moss and leaves.'],
    hint: 'A cool pond with water plants and a wooded bank.',
  },
  sumatra: {
    id: 'sumatra', name: 'Sumatran lowland river', country: 'Indonesia', level: 5,
    animals: ['loach'], plants: ['javafern', 'javamoss', 'fern', 'grass', 'pothos', 'rotala', 'vallisneria', 'crypt'],
    climate: { temp: [24, 30], humidity: [70, 100] },
    features: ['deep', 'wood', 'oxygen'],
    blurb: 'Large lowland rivers of Sumatra and Borneo, brown with silt in the rains. Clown loaches live in groups among roots and sunken wood and move into flooded areas to spawn.',
    facts: ['Clown loaches click with their teeth.', 'They can grow to 30 cm and live for decades.'],
    hint: 'Deep, warm, moving water with roots and wood; a big tank.',
  },
  thai: {
    id: 'thai', name: 'Central Thai klong', country: 'Thailand', level: 5,
    animals: ['betta'], plants: ['lily', 'cattail', 'rotala', 'grass', 'javafern', 'fern', 'pothos', 'vallisneria', 'javamoss', 'crypt'],
    climate: { temp: [24, 30], humidity: [70, 90] },
    features: ['stillwater', 'deep'],
    blurb: 'Canals, marshes and paddies of the central plain of Thailand: shallow, warm, still and thick with plants. Wild bettas live at the edges and breathe air at the surface.',
    facts: ['Bettas have a labyrinth organ that lets them breathe air.', 'Males build a nest of bubbles at the surface and guard the eggs.'],
    hint: 'Still, warm water with floating and stem plants; no strong flow.',
  },
  shan: {
    id: 'shan', name: 'Shan Plateau spring pond', country: 'Myanmar', level: 5,
    animals: ['cpd'], plants: ['grass', 'rotala', 'javamoss', 'vallisneria', 'crypt'],
    climate: { temp: [22, 26], humidity: [60, 90] },
    features: ['stillwater', 'cycled'],
    blurb: 'Small, shallow spring-fed ponds on the Shan Plateau about 1,000 m up, thick with grass and stems. The celestial pearl danio was described only in 2007.',
    facts: ['The fish became a hit in the trade within months of its discovery.', 'Males spar with fin displays.'],
    hint: 'Clear, shallow water with dense plants; gentle flow.',
  },
  taiwan: {
    id: 'taiwan', name: 'Taiwan hill stream', country: 'Taiwan', level: 5,
    animals: ['blueshrimp', 'shrimp', 'springtail', 'isopod'], plants: ['javafern', 'javamoss', 'fern', 'grass', 'pothos', 'vallisneria', 'nidus', 'miscanthus', 'crypt'],
    climate: { temp: [18, 26], humidity: [70, 95] },
    features: ['stream', 'stones', 'moss15'],
    blurb: 'Streams and lakes in the hills of Taiwan, home of the wild Neocaridina shrimp from which cherry and blue dream shrimp were bred. Wild ones are brown and clear.',
    facts: ['Every coloured strain comes from the same wild species.', 'They graze biofilm off every surface.'],
    hint: 'Clear water, moss, stones and wood to graze.',
  },
  putumayo: {
    id: 'putumayo', name: 'Putumayo forest creek', country: 'Peru', level: 5,
    animals: ['neon'], plants: ['sword', 'frogbit', 'fern', 'grass', 'monstera', 'bromeliad'],
    climate: { temp: [21, 26], humidity: [70, 100] },
    features: ['wood', 'deep'],
    blurb: 'Shaded forest creeks in the upper Amazon basin of Peru and Colombia, with soft, slightly acid water. Neon tetras school in the dim water under overhanging plants.',
    facts: ['Nearly all neons in shops are farmed now.', 'Their blue stripe shifts colour with the angle of the light.'],
    hint: 'Soft water, shade, wood and a school of neons.',
  },
  araguaia: {
    id: 'araguaia', name: 'Araguaia basin backwater', country: 'Brazil', level: 5,
    animals: ['ember'], plants: ['sword', 'frogbit', 'lily', 'grass', 'vallisneria', 'fern'],
    climate: { temp: [23, 29], humidity: [65, 95] },
    features: ['stillwater', 'deep'],
    blurb: 'Warm, still backwaters of the Rio das Mortes in the Araguaia basin of central Brazil, rich in plants. The ember tetra lives here in schools.',
    facts: ['The species was named after Amanda Bleher, the mother of the collector Heiko Bleher.', 'It is one of the smallest tetras.'],
    hint: 'Warm, still, planted water.',
  },
  trinidad: {
    id: 'trinidad', name: 'Trinidad hill stream', country: 'Trinidad and Tobago', level: 5,
    animals: ['guppy', 'springtail', 'isopod'], plants: ['grass', 'fern', 'bromeliad', 'guzmania', 'monstera', 'tillandsia', 'heliconia'],
    climate: { temp: [22, 28], humidity: [70, 95] },
    features: ['stream', 'stones'],
    blurb: 'Clear streams of the Northern Range of Trinidad, where waterfalls divide them into stretches with and without big predators. Guppies here are a classic case of evolution in the wild.',
    facts: ['Above the falls, without predators, males are more colourful.', 'Guppies moved to new pools evolved within a few years.'],
    hint: 'A clear stream with pools and stones.',
  },
  tapajos: {
    id: 'tapajos', name: 'Tapajós clear-water sandbank', country: 'Brazil', level: 5,
    animals: ['cory'], plants: ['sword', 'vallisneria', 'grass', 'fern', 'frogbit'],
    climate: { temp: [24, 29], humidity: [65, 95] },
    features: ['wood', 'deep', 'cycled'],
    blurb: 'The Rio Tapajós carries clear, blue-green water over white sand. In the dry season wide sandbanks appear, and corydoras sift the sand at their edges for worms and insect larvae.',
    facts: ['Corydoras can breathe air through their gut and dart to the surface for a gulp.', 'They have sharp spines in their fins as a defence.'],
    hint: 'Fine sand, wood and clear water; a group of corydoras.',
  },
  mataatlantica: {
    id: 'mataatlantica', name: 'Atlantic rainforest creek', country: 'Brazil', level: 5,
    animals: ['oto'], plants: ['sword', 'sinningia', 'neoregelia', 'fern', 'grass', 'tillandsia', 'columnea'],
    climate: { temp: [22, 27], humidity: [75, 100] },
    features: ['stream', 'bromeliad2'],
    blurb: 'The Atlantic rainforest along the coast of south-eastern Brazil, much of it cleared, is rich in species found nowhere else. Otocinclus graze algae off leaves and wood in its small creeks.',
    facts: ['Less than an eighth of the original Atlantic forest remains.', 'Sinningia pusilla, one of the smallest gloxinias, grows on wet rock here.'],
    hint: 'Clear water with plants to graze, wet rock with small epiphytes.',
  },
  kerala: {
    id: 'kerala', name: 'Kerala paddy pool', country: 'India', level: 5,
    animals: ['snail'], plants: ['rotala', 'lily', 'grass', 'cattail', 'vallisneria', 'crypt'],
    climate: { temp: [22, 30], humidity: [70, 95] },
    features: ['stillwater', 'shallowpool'],
    blurb: 'Paddies and pools on the red laterite soils of Kerala fill with the monsoon. The trumpet snail is native here and burrows in the mud by day.',
    facts: ['Trumpet snails give birth to live young.', 'They aerate the substrate as they burrow.'],
    hint: 'Warm, still water over a soft bottom.',
  },
  thaicave: {
    id: 'thaicave', name: 'Thai limestone cave mouth', country: 'Thailand', level: 5,
    animals: ['pandaking', 'springsea'], plants: ['javamoss', 'javafern', 'fern', 'pothos', 'nidus'],
    climate: { temp: [24, 28], humidity: [80, 95] },
    features: ['stones', 'moss15', 'shallowpool'],
    blurb: 'Tower karst covers much of southern Thailand. At cave mouths, seeps keep the rock wet and mossy, and many isopods found nowhere else live in the leaf litter and on the limestone.',
    facts: ['Isopods breathe through gill-like organs and need damp air.', 'Limestone gives them the calcium for their shells.'],
    hint: 'Damp limestone, moss, litter and a seep.',
  },
  litterjar: {
    id: 'litterjar', name: 'Forest-floor litter (hobby cultures)', country: 'origin not verified', level: 5,
    animals: ['purpleiso', 'springpink', 'isopod', 'springtail'], plants: ['fern', 'grass', 'javamoss'],
    climate: { temp: [22, 26], humidity: [85, 100] },
    features: ['leaflitter'],
    blurb: 'A crew culture: the wild origin of these isopods and springtails is not known. They live in damp litter and break down dead plant matter.',
    facts: ['Springtails are not insects: they are a separate group of six-legged animals.', 'Isopods are crustaceans, related to shrimp and crabs.'],
    hint: 'Damp litter, rotting wood and moss.',
  },
};

Object.assign(BIOTOPES, SHOWCASE_BIOTOPES);   // run "sets": the canyon's and the highland's real places

export const BIOTOPE_ORDER = ['suriname', 'blackwater', 'bocas', 'java', 'pacific', 'korea', 'china', 'xochimilco'];
