// Real habitats to copy. Each says what the place is like (temperature and
// humidity targets from field data), who lives there (animals and plants the
// game has), and which features make it recognisable. The Curator scores a
// tank against its chosen biotope; commissions ask for them by name.

export const BIOTOPES = {
  newguinea: {
    id: 'newguinea', name: 'New Guinea stream bank', country: 'Papua New Guinea', level: 7,
    animals: ['skink', 'purpleiso', 'springtail'], plants: ['fernph', 'pothos', 'bromeliad', 'weed'],
    climate: { temp: [23, 28], humidity: [80, 98] },
    features: ['leaflitter', 'shallowpool', 'basking', 'uvb'],
    blurb: 'Humid lowland forest floor beside a creek: deep leaf litter, rotting logs and the roots of sago palms. The red-eyed crocodile skink lives here, hidden by day and out at dusk to hunt insects and worms along the water.',
    facts: ['The skink lays a single egg at a time, often in a damp burrow under a log.', 'Crocodile skinks can squeak: one of the few lizards that make a sound when handled.'],
    hint: '80% land with deep litter, cork and wood to hide under, a shallow pool, a mild warm spot and low UVB, 80% humidity or more.',
  },
  madagascar: {
    id: 'madagascar', name: 'Madagascar reed marsh', country: 'Madagascar', level: 6,
    animals: ['reedfrog', 'springtail', 'fly'], plants: ['cattail', 'bamboo', 'bromeliad', 'pothos', 'frogbit'],
    climate: { temp: [24, 29], humidity: [70, 90] },
    features: ['deep', 'tall4', 'bromeliad2'],
    blurb: 'Reeds and shrubs around marshes and paddies in southern and eastern Madagascar. Starry night reed frogs sit high on stems and leaves above the water by day and call in chorus from them in the rainy season.',
    facts: ['Reed frogs sit flat on a leaf with their legs tucked in to save water in the heat of the day.', 'Their eggs are laid in the water below, so the tadpoles drop straight into a pond.'],
    hint: 'A tall tank, mostly water, with broad leaves, reeds and stems above it to perch on.',
  },
  matano: {
    id: 'matano', name: 'Lake Matano shore', country: 'Indonesia', level: 7,
    animals: ['panther', 'snail'], plants: ['javafern', 'vallisneria'],
    climate: { temp: [24, 28], humidity: [70, 100] },
    features: ['deep', 'hardwater', 'stones', 'wood'],
    blurb: 'An ancient, very deep lake in the mountains of Sulawesi with clear, warm, alkaline water. Panther crabs live among the rocks and sunken wood of its shore, beside snails and shrimp found nowhere else.',
    facts: ['Lake Matano is more than a million years old and 590 m deep, one of the oldest lakes on Earth.', 'Its water is low in nutrients and rich in minerals, so it is extremely clear.'],
    hint: 'Deep, hard water (GH 10 or more), stones and wood that reach out of it, strong filtration.',
  },
  everglades: {
    id: 'everglades', name: 'Everglades swamp margin', country: 'United States', level: 5,
    animals: ['pygmy', 'springtail', 'isopod'], plants: ['cattail', 'grass', 'frogbit', 'weed'],
    climate: { temp: [18, 26], humidity: [65, 95] },
    features: ['stillwater', 'shallowpool', 'moss15'],
    blurb: 'Weedy, still margins of the Florida swamps, thick with stems, floating plants and mats of vegetation. The Everglades pygmy sunfish hangs among the stems waiting for tiny crustaceans to drift by.',
    facts: ['The swamp cools in winter: these fish need a cooler spell to breed well.', 'A displaying male turns velvet black with blue spangles.'],
    hint: 'Still water, thick with stems and floating plants; no strong filter.',
  },
  suriname: {
    id: 'suriname', name: 'Suriname forest island', country: 'Suriname', level: 4,
    animals: ['dartfrog', 'springtail', 'isopod', 'fly'], plants: ['bromeliad', 'fernph', 'fern', 'pothos', 'grass', 'guzmania'],
    climate: { temp: [23, 28], humidity: [80, 97] },
    features: ['bromeliad2', 'leaflitter', 'shallowpool'],
    blurb: 'Islands of forest in open savanna. Days are warm and humid, nights cooler, and there is a clear wet and dry season. The blue poison frog lives among the roots and leaf litter of these islands and its tadpoles grow in bromeliad cups.',
    facts: ['The savanna between the forest islands is dry and bright, so each island is a pocket of moisture the frogs cannot leave.', 'Each island holds its own small frog population, which is why so many local colour forms exist.'],
    hint: 'Dense plants and moss on the ground, bromeliads above the waterline, a shallow pool, 80%+ humidity.',
  },
  bocas: {
    id: 'bocas', name: 'Bocas del Toro lowland forest', country: 'Panama', level: 5,
    animals: ['strawberry', 'springtail', 'isopod', 'fly'], plants: ['bromeliad', 'fern', 'fernph', 'grass', 'pothos', 'guzmania', 'columnea'],
    climate: { temp: [24, 29], humidity: [85, 100] },
    features: ['bromeliad3', 'moss15', 'stream'],
    blurb: 'Rain falls on more than 200 days a year on the Caribbean coast of Panama. Strawberry poison frogs live in leaf litter and low bromeliads. Each island has its own colour, from red with blue legs to green, orange and white.',
    facts: ['Females feed their tadpoles unfertilised eggs, one tadpole per bromeliad.', 'The frogs are tiny: an adult is under 2.5 cm long.'],
    hint: 'Constant humidity, lots of moss and litter, three or more bromeliads, and a small stream.',
  },
  blackwater: {
    id: 'blackwater', name: 'Rio Negro blackwater', country: 'Brazil', level: 4,
    animals: ['cardinal', 'neon', 'cory', 'shrimp'], plants: ['sword', 'javafern', 'vallisneria'],
    climate: { temp: [24, 29], humidity: [70, 100] },
    features: ['wood', 'deep', 'cycled'],
    blurb: 'The Rio Negro is stained the colour of tea by tannins from the forest. The water is acidic and nearly sterile. Fish here live among fallen wood, leaf litter and the trunks of trees that flood every year.',
    facts: ['Blackwater has almost no nutrients, so few aquatic plants can grow in it. Most of the food comes from the forest.', 'The tannins stain light, so the river looks black from above.'],
    hint: 'A deep lagoon, driftwood, a school of small tetras, and clean cycled water.',
  },
  korea: {
    id: 'korea', name: 'Korean mountain stream', country: 'South Korea', level: 6,
    animals: ['toad', 'springtail', 'isopod', 'fly'], plants: ['grass', 'fernph', 'weed', 'bilberry'],
    climate: { temp: [16, 24], humidity: [60, 90] },
    features: ['stream', 'shallowpool', 'moss15'],
    blurb: 'Cool hills with slow streams and rice paddies. The fire-bellied toad lives in ponds and stream margins where the water is shallow and the temperature rarely rises above the low twenties.',
    facts: ['It hibernates in winter, and the cold snap helps trigger breeding in spring.', 'It is common enough to be found in paddies.'],
    hint: 'Cool: keep it under 24 °C with a fan or a cooling unit; ferns and grass, a slow stream, a shallow pool.',
  },
  china: {
    id: 'china', name: 'Chinese mountain torrent', country: 'China', level: 7,
    animals: ['newt', 'shrimp', 'springtail'], plants: ['javafern', 'fernph', 'weed'],
    climate: { temp: [14, 23], humidity: [70, 95] },
    features: ['falls', 'oxygen', 'stones'],
    blurb: 'Cool, shaded, fast streams under mixed forest. The paddle-tailed newt clings to the bottom under stones in fast, well-oxygenated water.',
    facts: ['Oxygen dissolves better in cold, turbulent water.', 'Many of these streams are shrinking as forests are cleared.'],
    hint: 'A waterfall for oxygen, cool water (under 23 °C), lots of stones.',
  },
  java: {
    id: 'java', name: 'Javan stream bank', country: 'Indonesia', level: 5,
    animals: ['crab', 'shrimp', 'isopod', 'springtail'], plants: ['fern', 'fernph', 'pothos', 'weed'],
    climate: { temp: [24, 29], humidity: [80, 98] },
    features: ['shallowpool', 'moss15', 'stones'],
    blurb: 'On the forest floor of Java, small streams run over volcanic rock. Vampire crabs live on the banks: half on land, half in water, and breed on land.',
    facts: ['They dig burrows in the wet soil beside streams.', 'The young are miniature crabs that skip the swimming larval stage.'],
    hint: 'Damp soil, stones, shallow water and land beside it; a lid.',
  },
  xochimilco: {
    id: 'xochimilco', name: 'Xochimilco canals', country: 'Mexico', level: 8,
    animals: ['axolotl', 'shrimp'], plants: ['vallisneria', 'javafern', 'frogbit'],
    climate: { temp: [14, 20], humidity: [50, 95] },
    features: ['deep', 'cycled', 'cool'],
    blurb: 'A network of canals in the south of Mexico City: the last home of the axolotl. Cool, shallow water beside floating gardens, at 2,200 metres above sea level.',
    facts: ['Introduced carp and tilapia eat axolotls and their eggs, and pollution threatens the water.', 'Local farmers build reed-fenced refuges to protect the animals.'],
    hint: 'Cold water (under 20 °C): needs a cooling unit. Clean, planted and cool.',
  },
  pacific: {
    id: 'pacific', name: 'Pacific palm grove', country: 'Fiji', level: 5,
    animals: ['gecko', 'fly', 'springtail'], plants: ['pothos', 'bromeliad', 'grass', 'fern'],
    climate: { temp: [23, 30], humidity: [55, 85] },
    features: ['tall4', 'basking'],
    blurb: 'On Pacific islands mourning geckos live in palms, on walls and roofs, and hunt around lamps at night. They favour warm, humid but airy places, with plenty to climb.',
    facts: ['They colonised islands across the Pacific by rafting on floating debris.', 'They call with a soft chirp.'],
    hint: 'Vertical plants and a basking spot; less soggy than a frog tank.',
  },
};

export const BIOTOPE_ORDER = ['suriname', 'blackwater', 'bocas', 'java', 'pacific', 'korea', 'china', 'xochimilco'];
