// Field-guide entries for plants: what they are, where they come from and the
// job they do in a living tank.

export const PLANT_INFO = {
  fernph: {
    sci: 'Athyrium filix-femina', region: 'Temperate forests of the northern hemisphere',
    role: 'Shade cover and humidity',
    facts: ['Ferns are older than flowers: they reproduce with spores, released from the brown dots under the fronds, not with seeds.', 'Each frond unrolls from a curled "fiddlehead". The fern is a tell-tale of a moist, shaded, undisturbed forest floor.'],
    care: ['Loves shade and damp air; leaves crisp and brown when the air is dry.', 'Its leaves shade the ground below: a fern canopy can lower the light that reaches moss.'],
    lesson: 'photoperiod',
  },
  weed: {
    sci: 'Lysimachia nummularia', region: 'Europe, naturalised elsewhere',
    role: 'Ground cover; softens rock edges',
    facts: ['Creeping jenny, or moneywort, spreads by trailing stems that root wherever they touch damp soil: a living carpet.', 'Its coin-shaped leaves give it its Latin name: nummularia means "coin-like".'],
    care: ['Trims easily. Will happily trail into shallow water.'],
    lesson: 'succession',
  },
  fern: {
    sci: 'Nephrolepis and relatives', region: 'Tropics worldwide',
    role: 'Understorey; transpiration',
    facts: ['Tropical ferns can move a lot of water: transpiration from a dense fern floor is a large part of a rainforest\'s humidity.'],
    care: ['Needs damp air. Feeds through its roots, so leaf litter helps.'],
    lesson: 'water-cycle',
  },
  bilberry: {
    sci: 'Vaccinium myrtillus (as a stand-in for small shrubs)', region: 'Cool forests and heaths of Europe and Asia',
    role: 'Structure; height',
    facts: ['A small woody shrub gives a tank a "middle layer" between moss and the canopy.'],
    care: ['Needs good light and airy conditions.'],
    lesson: 'composition',
  },
  grass: {
    sci: 'Poaceae', region: 'Worldwide',
    role: 'Fine texture; waterside cover',
    facts: ['Grasses grow from the base of the leaf, not the tip, so they survive grazing and mowing. That is why a lawn can be cut.'],
    care: ['Likes bright light.'],
    lesson: 'composition',
  },
  bromeliad: {
    sci: 'Bromeliaceae (e.g. Neoregelia, Vriesea)', region: 'Central and South America',
    role: 'Tadpole nursery; epiphyte',
    facts: [
      'Many bromeliads grow on tree branches high in the forest and have leaves arranged in a cup that holds rainwater: a tiny pond in the sky.',
      'These "phytotelmata" are full of life: insect larvae, frogs and tadpoles. Poison frogs carry their tadpoles up into the trees and deposit one in each cup.',
      'Bromeliads take nutrients from the water and debris in the cup, not just the roots: the roots mostly cling.',
    ],
    care: ['Mount it high on the background. Keep water in the cup.', 'Bright but not harsh light.'],
    lesson: 'parental-care',
  },
  pothos: {
    sci: 'Ficus pumila', region: 'East Asia',
    role: 'Living background: covers the wall',
    facts: ['Creeping fig has two kinds of leaf: small, heart-shaped juvenile leaves that climb by clinging roots, and much larger adult leaves and fruit.'],
    care: ['Hides a plain background quickly: keep it trimmed so it does not smother other plants.'],
    lesson: 'composition',
  },
  cattail: {
    sci: 'Typha', region: 'Wetlands worldwide',
    role: 'Waterline plant; filters water',
    facts: ['Cattails grow in shallow water and take up nitrogen and phosphorus. Constructed wetlands with cattails are used to clean sewage and runoff.', 'The brown "cat tail" is a dense spike of thousands of tiny flowers.'],
    care: ['Needs its roots in wet ground and its leaves in the air.'],
    lesson: 'nitrogen-cycle',
  },
  bamboo: {
    sci: 'Cyperus involucratus', region: 'Africa and Madagascar; naturalised elsewhere',
    role: 'Waterline plant; vertical structure',
    facts: ['A sedge, not a grass: its stems are triangular in cross-section. The "umbrella" is a whorl of leaf-like bracts at the top.', 'It grows in swamps and along rivers where the soil is always wet.'],
    care: ['Likes to stand in shallow water.'],
    lesson: 'nitrogen-cycle',
  },
  vallisneria: {
    sci: 'Vallisneria', region: 'Tropical and temperate fresh waters',
    role: 'Underwater grass: uses nitrate, makes oxygen',
    facts: ['Vallisneria pollination is remarkable: male flowers break loose, float to the surface and drift until they bump into a female flower, which is held on a long stalk at the surface.', 'It spreads by runners, and a few plants make a meadow.'],
    care: ['Needs light. It takes up nitrate from the water.'],
    lesson: 'nitrogen-cycle',
  },
  sword: {
    sci: 'Echinodorus', region: 'Central and South America',
    role: 'Centrepiece for the aquatic floor',
    facts: ['A rosette plant: a big root system feeds heavily from the substrate.', 'The leaves come in two forms: submerged and, if it grows above the surface, tougher emergent leaves.'],
    care: ['Hungry. Needs a nutrient-rich substrate or fertiliser.'],
    lesson: 'photoperiod',
  },
  javafern: {
    sci: 'Microsorum pteropus', region: 'South-east Asia',
    role: 'Low-light plant for wood and stone',
    facts: ['A fern that lives underwater. It grows attached to rocks and wood, not planted in the substrate, so burying the rhizome kills it.', 'It grows slowly, so it uses little light and nutrients: hard to kill.'],
    care: ['Tie it to rock or wood. Shade is fine.'],
    lesson: 'photoperiod',
  },
  fissidens: {
    sci: 'Fissidens fontanus', region: 'North America (and relatives worldwide)',
    role: 'Dense cover and grazing for shrimp under water',
    facts: ['Each frond is a flat feather: the leaves sit in two rows, folded and clasping the stem.', 'Unlike java moss it hardly drifts: it grows slowly into a tight cushion that holds onto wood and stone.'],
    care: ['Low light and soft, clean water; tie it to wood or stone.', 'Slow: weeks before it fills in, months to cover a branch.'],
    lesson: 'bioactive',
  },
  rotala: {
    sci: 'Rotala rotundifolia', region: 'South and South-East Asia',
    role: 'Fast nitrate uptake; a background bush',
    facts: ['A stem plant: it grows at the tips and is propagated by cutting the tops off and pushing them into the substrate.', 'Under strong light it makes red pigments (anthocyanins) at the tips, so a bright tank turns it pink.'],
    care: ['Bright light and nutrients; trim often, it races to the surface.', 'Above water it grows on as a creeping emersed form.'],
    lesson: 'nitrogen-cycle',
  },
  anubias: {
    sci: 'Anubias barteri', region: 'West and Central Africa',
    role: 'Tough, low-light plant for wood, stone and the water\'s edge',
    facts: ['In the wild it grows along streams, often half out of the water, so it does as well above the surface as below it.', 'Its leaves are thick and leathery: fish and snails leave them alone, and toads rest on them.'],
    care: ['Tie the rhizome to wood or stone; never bury it.', 'Grows slowly in shade: algae can settle on old leaves in strong light.'],
    lesson: 'photoperiod',
  },
  javamoss: {
    sci: 'Taxiphyllum barbieri', region: 'South-east Asia',
    role: 'Cover and grazing for fry, shrimp and danios',
    facts: ['A true moss that grows in and out of water on wet wood and stone.', 'Its tangle traps detritus, which grows a film of microbes: food for baby shrimp and newly hatched fish.'],
    care: ['Attach it to wood or stone; trim it so the inside does not rot.'],
    lesson: 'bioactive',
  },
  monstera: {
    sci: 'Monstera adansonii', region: 'Central and South America',
    role: 'Big-leaved climber for the background',
    facts: ['A climbing aroid: aerial roots grip bark and stone as it climbs toward the light.', 'In the wild its leaves are full of holes, which may let light and wind through to the leaves below.'],
    care: ['Let it climb the background; trim it before it shades the whole tank.'],
    lesson: 'humidity',
  },
  frogbit: {
    sci: 'Limnobium laevigatum', region: 'South and Central America',
    role: 'Floating cover: shades algae and takes up nutrients',
    facts: ['Floating plants take carbon dioxide from the air rather than the water, so they grow fast. Their roots hang in the water and absorb nutrients directly.', 'A carpet of frogbit blocks light from reaching algae: a floating plant is one of the strongest ways to suppress an algae bloom.'],
    care: ['Multiplies fast. Thin it out or it will shade everything below.'],
    lesson: 'algae',
  },
  lily: {
    sci: 'Nymphaea', region: 'Fresh waters worldwide',
    role: 'Surface cover; a focal point',
    facts: ['Water lily leaves have stomata on the upper surface, because the underside is in the water. The leaf stalk is hollow, and pumps air down to the roots buried in mud.', 'Flowers open by day (or by night, depending on the species) and are pollinated by beetles.'],
    care: ['Needs bright light and space on the surface.'],
    lesson: 'photoperiod',
  },
  // ---- Flowering plants (sim/flowering.js, 2026-10) ----
  masdevallia: {
    sci: 'Masdevallia (M. coccinea, M. veitchiana, M. ignea and hybrids)', region: 'Cloud forests of the Andes, Colombia to Peru',
    role: 'Colour on the background; a cool-tank orchid',
    facts: ['The "petals" you see are three sepals fused into a tube and drawn out into tails; the true petals and lip are tiny, hidden in the throat.', 'M. coccinea grows on open grassy slopes high in the Andes and comes in magenta, red, orange, yellow and white forms.', 'It has no pseudobulbs to store water, so it must never dry out.'],
    care: ['Cool (under 24 °C), humid, moving air and bright shade: a warm, stuffy tank kills it.', 'Mount it on cork or wood on the background; water often.'],
    lesson: 'microclimate',
  },
  dracula: {
    sci: 'Dracula (D. simia, D. vampira, D. bella and relatives)', region: 'Cloud forests of Ecuador, Colombia, Peru and Central America',
    role: 'A strange, hanging flower for a cool, misty tank',
    facts: ['"Dracula" means little dragon, after the long tails of the sepals; D. simia\'s flower looks like a monkey\'s face.', 'The lip smells of mushrooms and is shaped like the gills of one: it fools fungus gnats into pollinating it.', 'The flower stems grow out and down, so in the wild and in a basket the flowers hang below the plant.'],
    care: ['Cool, very humid and never still air: mist often but let the leaves dry between mistings.', 'Keep it in shade; mount it where its flowers can hang free.'],
    lesson: 'microclimate',
  },
  pleurothallis: {
    sci: 'Pleurothallis (heart-leaved group: P. cardiothallis, P. palliolata)', region: 'Montane forests of Central and South America',
    role: 'Epiphyte for the background; flowers that sit on the leaf',
    facts: ['Each stem carries a single heart-shaped leaf, and the little flowers appear in the notch at its base, lying on the leaf.', 'Pleurothallids are one of the largest groups of orchids: thousands of species, many only a few centimetres tall.'],
    care: ['Humid shade and a moist mount; water often, with good air movement.', 'Intermediate temperatures; it dislikes heat.'],
    lesson: 'humidity',
  },
  lepanthes: {
    sci: 'Lepanthes (L. calodictyon, L. telipogoniflora and relatives)', region: 'Wet forests from Mexico to Bolivia and the Caribbean',
    role: 'A miniature for close viewing',
    facts: ['A whole plant can be smaller than a coin; its flowers are a few millimetres across and look like tiny insects.', 'The stems are sheathed in ribbed funnels, a feature that gives the "lepanthiform" sheath its name.', 'Some species are pollinated by fungus gnats tricked into mating with the flower.'],
    care: ['Always moist, never soggy: on moss, cork or a twig in a closed, misty tank.', 'Low light and cool to intermediate temperatures.'],
    lesson: 'conservation',
  },
  cuthbertsonii: {
    sci: 'Dendrobium cuthbertsonii', region: 'Mountain forests and mossy slopes of New Guinea, 750-3500 m',
    role: 'Huge, long-lasting flowers on a tiny plant',
    facts: ['A plant a few centimetres tall carries flowers up to 4 cm long that last for months, some for most of a year.', 'Wild plants come in red, orange, pink, yellow, purple and bicoloured forms, often side by side on one tree.', 'The dark leaves are covered in tiny warts (papillae).'],
    care: ['Cool, bright and never dry: water it every day or keep it on living moss.', 'It suffers above 25 °C; give it the coolest bright spot of the tank.'],
    lesson: 'genetics',
  },
  neoregelia: {
    sci: 'Neoregelia (miniature tubular species: N. ampullacea, N. lilliputiana, \'Fireball\')', region: 'Atlantic rainforest of Brazil',
    role: 'Tadpole nurseries on runners; colour on the background',
    facts: ['The miniatures grow as a chain of narrow rosettes joined by stolons, creeping along a branch: each tube holds a few millilitres of rain.', 'Poison frogs deposit tadpoles in these tiny cups, one per cup.', 'At flowering the heart of the rosette blushes and small violet flowers open in its water; afterwards the rosette makes pups and slowly dies.'],
    care: ['Bright light brings out the colour; keep water in the cups and flush them now and then.', 'Mount it on the background or a branch: the roots only hold on.'],
    lesson: 'parental-care',
  },
  guzmania: {
    sci: 'Guzmania lingulata', region: 'Central America, the Caribbean and northern South America',
    role: 'A long-lasting splash of colour; a water cup',
    facts: ['The bright "flower" is a star of bracts, modified leaves that last for months; the real flowers are small and white and open a few at a time.', 'Hummingbirds pollinate it, drawn by the red bracts.', 'Like most cup bromeliads it flowers once, then raises pups around its base.'],
    care: ['Bright shade and humid air; keep a little water in the cup.', 'Grow it on the background or on a branch; it rots in wet soil.'],
    lesson: 'parental-care',
  },
  tillandsia: {
    sci: 'Tillandsia ionantha', region: 'Mexico to Costa Rica',
    role: 'An air plant for wood and the dry upper corners',
    facts: ['It has no need of soil: its roots only anchor it, and scales (trichomes) on the leaves take up water and nutrients from the air and rain, which is why it looks silvery.', 'When it flowers the inner leaves turn red and violet tubular flowers stand out of the heart; then it makes pups.'],
    care: ['Bright light and moving air; it must dry within a few hours after a soaking or it rots.', 'Do not bury it: fix it to wood or the background.'],
    lesson: 'water-cycle',
  },
  sinningia: {
    sci: 'Sinningia pusilla and micro-miniature hybrids', region: 'Wet rock faces of south-eastern Brazil',
    role: 'A tiny flowering carpet for moss and rock',
    facts: ['One of the smallest flowering plants grown in terrariums: the leaves are about a centimetre long.', 'It grows from a tiny tuber and flowers almost without a break; seeds it drops come up by themselves in a humid tank.', 'It is a gesneriad, a relative of the African violet.'],
    care: ['Humid air, moderate light and a damp but airy spot on moss or rock.', 'If it dies back it may resprout from the tuber.'],
    lesson: 'succession',
  },
  columnea: {
    sci: 'Columnea microphylla and hybrids', region: 'Rainforests of Costa Rica and Panama',
    role: 'A trailing epiphyte with flowers for the background',
    facts: ['Called the goldfish vine for its hooded flowers; hummingbirds pollinate it, and it grows on tree branches with its stems hanging down.', 'After flowering it makes small white berries that birds eat and spread.'],
    care: ['Bright shade, humid air and an airy mount; trim the long stems.', 'Let the mount dry a little between waterings.'],
    lesson: 'humidity',
  },
  begonia: {
    sci: 'Begonia foliosa (and var. miniata)', region: 'Mountain forests of Colombia, Venezuela and Ecuador',
    role: 'Fine texture and small flowers for the middle layer',
    facts: ['Begonias have separate male and female flowers on the same plant; the female ones carry a winged seed capsule behind the petals.', 'Var. miniata, with red nodding flowers, is called the fuchsia begonia.'],
    care: ['Humid shade and a damp, airy soil; trim straggly stems.', 'Grows from cuttings: pieces root easily in moss.'],
    lesson: 'composition',
  },
};
